apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cht-core.fullname" . }}
  labels:
    {{- include "cht-core.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cht-core.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cht-core.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "cht-core.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: horti-data
          persistentVolumeClaim:
            claimName: horti-pvc
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: horti-data
              mountPath: /root
          env:
            - name: HORTI_BUILDS_SERVER
              value: {{ .Values.chtCore.buildsServer }}
            - name: COUCHDB_SERVER
              value: {{ .Values.chtCore.couchDbServer }}
            - name: PROTOCAL
              value: {{ .Values.chtCore.couchDbProtocal }}
            - name: COUCHDB_PASSWORD
              valueFrom:
                  secretKeyRef:
                    name: {{ .Values.chtCore.secrets }}
                    key: adminPassword
            - name: COUCHDB_USER
              value: {{ .Values.chtCore.couchDbUser }}
            - name: MEDIC_VERSION
              value: {{ .Values.chtCore.chtCoreVersion }}
            - name: COUCH_NODE_NAME
              value: {{ .Values.chtCore.couchDbNodeName }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
