{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cht-core.serviceAccountName" . }}
  labels:
{{ include "cht-core.labels" . | nindent 4 }}
{{- end -}}
